name: GitHub Pages

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Web Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --depth=10000
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - run: flutter pub get
      - run: flutter test
      - name: Build Web App
        run: flutter build web --base-href /flutter_crop/
      - name: Create Tar File
        run: tar -C build/web/ -zcvf build/web.tar.gz .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: build/web.tar.gz
  deploy:
    name: Deploy GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1